name: Metrics
on:
  # Schedule daily updates
  schedule:
    - cron: "0 0 * * *" # Adjust this cron schedule as needed
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push:
    branches:
      - "master"
      - "main"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Ensures the repository is checked out
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Your GitHub personal access token
          filename: metrics.plugin.activity.svg # Output file for the plugin
          base: "" # Base template (leave empty for default)
          plugin_activity: yes # Enable the Recent Activity plugin
          plugin_activity_limit: 5 # Show up to 5 recent activities
          plugin_activity_days: 14 # Include activities from the last 14 days
          plugin_activity_filter: issue, pr, release, push, star # Filter for specific event types
