name: Metrics
on:
  # Allow manual triggering of the workflow
  workflow_dispatch:
  # Schedule updates (each hour on weekdays)
  schedule:
    - cron: "30 * * * 1-5"
  workflow_call:
    secrets:
      METRICS_TOKEN:
        required: true

jobs:
  github-metrics:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: 📰 Recent Activity - Recent activity
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.activity.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 5
          plugin_activity_days: 0
          plugin_activity_filter: comment, ref/create, push, fork, star, public
          plugin_activity_skipped: |
            vincent-4
          output_action: commit
          delay: 120
          user: vincent-4
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
